conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('',views.inbox,name='inbox')
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views 
from .forms import LoginForm

app_name = 'core'
urlpatterns = [
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm),name='login')
]

items/urls.py
from django.urls import path
from . import views
app_name = 'items'

urlpatterns = [
    path('new/',views.newItem,name='newItem'),
    path('',views.items,name='items'),
    path('edit/<int:pk>',views.edit,name='edit'),
    path('delete/<int:pk>',views.delete,name='delete'),
    path('<int:pk>/',views.detail_view,name='detail')
]

onlineMarketPlace/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls')),
    path('',include('core.urls')),
    path('items/',include('items.urls')),
    path('inbox/',include('conversation.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images',blank=True,null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)


            

items/forms.py
from django import forms
from .models import Item
INPUT_CLASSES = 'w-full py-4 px-6 rouned-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['category','name','description','price','image']
        widgets = {
        'category' : forms.Select(attrs={
        'class' : INPUT_CLASSES
        }),
        'name' : forms.TextInput(attrs={
        'class' : INPUT_CLASSES
        }),
        'description': forms.Textarea(attrs={
        'class': INPUT_CLASSES
        }),
        'price' : forms.TextInput(attrs={
        'class':INPUT_CLASSES
        }),
        'image' : forms.FileInput(attrs={
        'class' : INPUT_CLASSES
        })
        }
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name','description','price','image','is_sold']
        widgets = {
        'name' : forms.TextInput(attrs={
        'class' : INPUT_CLASSES
        }),
        'description': forms.Textarea(attrs={
        'class': INPUT_CLASSES
        }),
        'price' : forms.TextInput(attrs={
        'class':INPUT_CLASSES
        }),
        'image' : forms.FileInput(attrs={
        'class' : INPUT_CLASSES
        })
        }
        

items/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from .models import Item,Category
from .forms import NewItemForm,EditItemForm
# Create your views here.

def detail_view(request,pk):
    
   
    item = get_object_or_404(Item,pk=pk)
    related_items = Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:3]
#     return HttpResponse(request,'hi there testing')
    return render(request,'details.html',{
          'item' : item,
          'related_items' : related_items
    }) 

@login_required
def newItem(request):
    
      form = NewItemForm(request.POST,request.FILES)
      if request.method == 'POST':
            if form.is_valid():
                  item = form.save(commit=False)
                  item.created_by = request.user
                  item.save()
                  return redirect('items:detail',pk=item.id)
            else:
                 form = NewItemForm()
      
      return render(request,'form.html',{
            'form':form
    })

@login_required
def delete(request,pk):
     item = get_object_or_404(Item,pk=pk)
     item.delete()
     return redirect('dashboard:index')

@login_required
def edit(request,pk):
     item = get_object_or_404(Item,pk=pk)
     form = EditItemForm(instance=item)
     if request.method == 'POST':
      form = EditItemForm(request.POST,request.FILES,instance=item)
      if form.is_valid():
            form.save()
            return redirect('items:detail',pk=item.id)
      
     return render(request,'edit.html',{
          'form' : form
     })

# for browsing

def items(request):
     query = request.GET.get('query','')
     category_id = request.GET.get('category',0)
     categories = Category.objects.all()
     items = Item.objects.filter(is_sold=False)
     if category_id:
          items = items.filter(category_id = category_id)
     if query:
          items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
          
      
     return render(request,'items.html',{
           'items' : items,
           'query' : query,
           'categories' : categories,
           'category_id' : int(category_id)
      })

items/templates/details.html
{% extends 'main.html' %} {% block content%}
<div class="grid grid-cols-6">
  {% if item.image %}
  <div class="col-span-3">
    <img src="{{ item.image.url }}" class="rounded-xl" alt="" />

    {%else%}
    <p class="text-center">This item has no image.</p>
    {% endif %}
  </div>
  <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
    <p class="text-gray-500"><strong>Price:</strong>{{ item.price }}</p>
    <p class="text-gray-500"><strong>Seller:</strong>{{ item.created_by }}</p>
    {%if item.description%}
    <p class="text-gray-500">
      <strong>Description</strong><br />
      {{ item.description }}
    </p>
    {%endif%} {%if request.user == item.created_by %}
    <div class="mt-6 p-6 bg-white rounded-xl">
      <p class="text-center">This is your item!</p>
      <a
        href="{% url 'items:edit' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl"
        >Edit</a
      >
      <a
        href="{% url 'items:delete' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl"
        >Delete</a
      >
    </div>
    {%else%}
    <a
      href="{% url 'conversation:new' item.id %}"
      class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-400 text-white rounded-xl hover:bg-teal-700"
    >
      Contact Seller
    </a>
    {%endif%}
  </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Related Items</h2>
  <div class="grid grid-cols-3 gap-3">
    {% for item in related_items %}
    <div>
      <a href="{% url 'items:detail' item.id %}">
        <div>
          <img src="{{ item.image.url }}" class="rounded-t-xl" alt="" />
        </div>
        <div class="p-6 bg-white rounded-b-xl">
          <h2 class="test-2xl">{{ item.name }}</h2>
          <p class="text-gray-500">Price: {{ item.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

{%endblock%}

items/templates/edit.html
{% extends 'main.html' %} {% block content%}
<h1 class="mb-6 text-3xl">Edit Item</h1>
<form action="" method="post" enctype="multipart/form-data">
  {%csrf_token%}
  <div class="space-y-4">{{ form.as_p }}</div>

  {% if form.errors or form.non_field_errors %}
  <div class="mb-3 p-6 bg-red-100 rounded-xl">
    {%for field in form%} {{ field.errors }} {%endfor%} {{ form.non_field_errors
    }}
  </div>
  {%endif%}

  <button
    class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"
  >
    Submit
  </button>
</form>
{%endblock%}

items/templates/form.html
{% extends 'main.html' %} {% block content%}
<h1 class="mb-6 text-3xl">New Item</h1>
<form action="." method="post" enctype="multipart/form-data">
  {%csrf_token%}
  <div class="space-y-4">{{ form.as_p }}</div>

  {% if form.errors or form.non_field_errors%}
  <div class="mb-3 p-6 bg-red-100 rounded-xl">
    {%for field in form%} {{ field.errors }} {%endfor%} {{ form.non_field_errors
    }}
  </div>
  {%endif%}

  <button
    class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"
  >
    Submit
  </button>
</form>
{%endblock%}

items/templates/items.html
{% extends 'main.html'%} {%block content%}

<div class="pb-6 grid grid-cols-4 gap-4">
  <div class="col-span-1">
    <form action="{%url 'items:items'%}" method="get">
      <span>
        <input
          type="text"
          name="query"
          class="w-full py-4 border rounded-xl"
          value="{{ query }}"
          placeholder="Find something here."
        />
         <button type="button" id="clearButton" class="ml-2 py-4 px-4 text-lg bg-red-500 text-white rounded-xl">
      Clear
    </button>
      </span>
      <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">
        Search
      </button>
    </form>
    <hr class="my-6" />
    <p class="font-semibold mb-3">Categories</p>
    <ul>
      {% for category in categories %}
      <li
        class="py-2 px-1 rounded-xl {%if category.id == category_id%} bg-gray-100 {%endif%} mb-3 text-center"
      >
        <a
          href="{%url 'items:items'%}?query={{query}}&category={{category.id}} "
        >
          {{ category.name }}
        </a>
      </li>
      {%endfor%}
    </ul>
  </div>
  <div class="col-span-3">
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
      <h2 class="mb-12 text-2xl text-center">Newest Items</h2>
      <div class="grid grid-cols-3 gap-3">
        {%for item in items%}
        <div>
          <a href="{% url 'items:detail' item.id %}">
            <div>
              {% if item.image %}
              <img src="{{ item.image.url }}" class="rounded-t-xl" alt="none" />
              {%else%}
              <p class="text-center p-6 bg-gray-200">This item has no image.</p>
              {% endif %}
            </div>
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="test-2xl">{{ item.name }}</h2>
              <p class="text-gray-500">Price: {{ item.price }}</p>
            </div>
          </a>
        </div>
        {%endfor%}
      </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
      <h2 class="mb-12 text-2xl text-center">Categories</h2>
      <div class="grid grid-cols-3 gap-3">
        {%for category in categories%}
        <div>
          <a href="">
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="test-2xl">{{ category.name }}</h2>
              <p class="text-gray-500">{{ category.items.count }}</p>
            </div>
          </a>
        </div>
        {%endfor%}
      </div>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const clearButton = document.getElementById("clearButton");
    const inputField = document.querySelector('input[name="query"]');

    clearButton.addEventListener("click", function () {
      inputField.value = "";
    });
  });
</script>

{%endblock%}